environment:
  nodejs_version: "Stable"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - npm test

build_script:
  - npm run deploy
